version: "3.1"

services:
  db:
    build:
      context: .
      dockerfile: db.dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
      - ./smrpy:/smrpy
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.docker-compose:/etc/nginx/conf.d/cbsmr.conf
      - ./smrpy/socket:/cbsmr/smrpy/socket
    ports:
      - "80:80"
      - "8000:8000"
  flask:
    build:
        context: .
        dockerfile: flask.dockerfile
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_DB=postgres
    volumes:
      - ./smrpy/socket:/cbsmr/smrpy/socket
    depends_on:
      - "db"
      - "nginx"
